# Generated by Django 3.2.13 on 2022-05-17 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(help_text='Įveskite valstybinius numerius', max_length=200, verbose_name='Valstybinis_NR')),
                ('vin_number', models.CharField(help_text='Įveskite automobilio VIN kodą', max_length=200, verbose_name='VIN_kodas')),
                ('client', models.CharField(help_text='Įveskite kliento vardą', max_length=200, verbose_name='Klientas')),
            ],
            options={
                'db_table': 'Automobilis',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Įveskite markę (pvz. Daewoo)', max_length=200, verbose_name='Markė')),
                ('model', models.CharField(help_text='Įveskite modelį (pvz. Matiz)', max_length=200, verbose_name='Modelis')),
            ],
            options={
                'db_table': 'Automobilio_modelis',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Užsakymo įvedimo data', verbose_name='Data')),
                ('amount', models.FloatField(help_text='Įveskite užsakymo sumą', verbose_name='Suma')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autoservisas_app.car')),
            ],
            options={
                'db_table': 'Uzsakymas',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(help_text='Įveskite užsakymo sumą', verbose_name='Kaina')),
                ('name', models.CharField(help_text='Įveskite paslaugos pavadinimą (pvz. Ratų keitimas)', max_length=200, verbose_name='Pavadinimas')),
            ],
            options={
                'db_table': 'Paslauga',
            },
        ),
        migrations.CreateModel(
            name='OrderRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Užsakymo įvedimo data', verbose_name='Data')),
                ('amount', models.FloatField(help_text='Įveskite užsakymo sumą', verbose_name='Suma')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autoservisas_app.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autoservisas_app.service')),
            ],
            options={
                'db_table': 'Uzsakymo_eilute',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(through='autoservisas_app.OrderRow', to='autoservisas_app.Service'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autoservisas_app.carmodel'),
        ),
    ]
