# Generated by Django 3.2.13 on 2022-05-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
    ]
