# Generated by Django 3.2.13 on 2022-05-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas_app', '0002_alter_carmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Gautas'), ('2', 'Patvirtintas'), ('3', 'Vykdomas'), ('4', 'Vėluojamas'), ('5', 'Atliktas')], default='1', help_text='Statusas', max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cars', to='autoservisas_app.carmodel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='autoservisas_app.car'),
        ),
    ]
