# Generated by Django 3.2.13 on 2022-05-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas_app', '0003_auto_20220523_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrow',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderrow',
            name='date',
        ),
        migrations.AddField(
            model_name='orderrow',
            name='price',
            field=models.FloatField(default=0, help_text='Įveskite kainą', verbose_name='Kaina'),
        ),
        migrations.AddField(
            model_name='orderrow',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Įveskite kiekį', verbose_name='Kiekis'),
        ),
        migrations.AlterField(
            model_name='orderrow',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='autoservisas_app.order'),
        ),
    ]
