# Generated by Django 3.2.13 on 2022-05-30 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas_app', '0004_auto_20220524_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_photo',
            field=models.ImageField(null=True, upload_to='car_photos', verbose_name='Automobilio nuotrauka'),
        ),
        migrations.AlterField(
            model_name='orderrow',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_rows', to='autoservisas_app.order'),
        ),
        migrations.AlterField(
            model_name='orderrow',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='service', to='autoservisas_app.service'),
        ),
    ]
