# Generated by Django 3.2.13 on 2022-05-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas_app', '0005_auto_20220530_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_photo',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_photo',
            field=models.ImageField(null=True, upload_to='car_photos', verbose_name='Automobilio nuotrauka'),
        ),
    ]
