# Generated by Django 3.2.13 on 2022-06-01 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservisas_app', '0006_auto_20220530_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrow',
            name='car_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderrow',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='Bus grąžinta'),
        ),
    ]
