# Generated by Django 3.2.13 on 2022-06-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas_app', '0010_orderreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(blank=True, help_text='Įveskite užsakymo sumą', null=True, verbose_name='Suma'),
        ),
    ]
