# Generated by Django 3.2.13 on 2022-06-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas_app', '0011_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.CharField(help_text="Enter client's name", max_length=200, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(help_text='Enter plate number', max_length=200, verbose_name='Plate_number'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_number',
            field=models.CharField(help_text="Enter car's plate number", max_length=200, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_photo',
            field=models.ImageField(null=True, upload_to='car_photos', verbose_name='Car photo'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='make',
            field=models.CharField(help_text='Enter make (e.g. Daewoo)', max_length=200, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(help_text='Enter model (e.g. Matiz)', max_length=200, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(blank=True, help_text='Leave empty', null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(help_text='Date of received order', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='Due_back'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Received'), ('2', 'Accepted'), ('3', 'In progress'), ('4', 'Overdue'), ('5', 'Done')], default='1', help_text='Status', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='orderrow',
            name='price',
            field=models.FloatField(default=0, help_text='Leave empty', verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderrow',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Enter quantity', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Enter service title (e.g. Change wheels)', max_length=200, verbose_name='Service title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(help_text='Enter service price', verbose_name='Price'),
        ),
    ]
