# Generated by Django 3.2.13 on 2022-06-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas_app', '0012_auto_20220621_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Date of received order', verbose_name='Date'),
        ),
    ]
