# Generated by Django 3.2.13 on 2022-06-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas_app', '0014_alter_car_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrow',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_rows', to='autoservisas_app.order'),
        ),
    ]
